blueprint:
  name: Door activated light
  description: Control lights based on door opening
  source_url: https://github.com/GordonFreemanK/ha-blueprints/blob/main/door_activated_light.yaml
  domain: automation
  input:
    door_sensors:
      name: Door sensors
      description: Which sensors should trigger the automation
      selector:
        entity:
          device_class: door
          multiple: true
    lights:
      name: Lights
      description: The lights to toggle
      selector:
        target:
          entity:
            domain: light
    brightness:
      name: Brightness
      description: The brightness to turn on the light at
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
      default: 80

mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input door_sensors

variables:
  door_sensors: !input door_sensors
  state: "{{ door_sensors | select('is_state', 'on') | list | length > 0 }}"

action:
- if:
  - condition: template
    value_template: "{{ state }}"
  then:
  - service: light.turn_on
    target: !input lights
    data:
      transition: 1
      brightness_pct: !input brightness
  else:
  - service: light.turn_off
    target: !input lights
    data:
      transition: 1
