blueprint:
  name: Hue button
  description: Toggle lights with Hue buttons
  source_url: https://github.com/GordonFreemanK/ha-blueprints/blob/main/hue_button.yaml
  domain: automation
  input:
    buttons:
      name: Buttons
      description: The buttons that toggle the lights
      selector:
        device:
          filter:
          - model: Hue smart button (8718699693985)
          multiple: true
    lights:
      name: Lights
      description: The lights to toggle with the buttons
      selector:
        entity:
          domain: light
          multiple: true
    brightness:
      name: Brightness
      description: The brightness to turn on the lights at
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
      default: 80
mode: restart
max_exceeded: silent

trigger:
- platform: mqtt
  topic: zigbee2mqtt/+/action

variables:
  device_name: "{{ trigger.topic | regex_replace('zigbee2mqtt/(.+)/action','\\g<1>') }}"
  payload: "{{ trigger.payload }}"
  buttons: !input buttons
  lights: !input lights
  state: "{{ expand(lights) | selectattr('state','eq','on') | list | length > 0 }}"

condition:
- condition: template
  value_template: "{{ device_name in buttons | map('device_attr','name') }}"
- condition: template
  value_template: "{{ payload in ['on','off'] }}"

action:
- if:
  - condition: template
    value_template: "{{ state }}"
  then:
  - service: light.turn_off
    target:
      entity_id: "{{ lights }}"
    data:
      transition: 1
  else:
  - service: light.turn_on
    target:
      entity_id: "{{ lights }}"
    data:
      transition: 1
      brightness_pct: !input brightness
- repeat:
    for_each: "{{ lights }}"
    sequence:
    - event: light_toggled
      event_data:
        state: "{{ not state }}"
        entity_id: "{{ repeat.item }}"
